name: Quality Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write


jobs:
  quality:

    runs-on: ubuntu-latest


    steps:



      # =========================
      # Descargar código
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check folders
        run: |
          pwd
          ls
          ls spring-petclinica || echo "NO EXISTE"
     
      # =========================
      # Java 21
      # =========================
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

    # =========================
      # Maven (IMPORTANTE: reemplaza mvnw)
      # =========================
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # =========================
      # Build Spring Boot
      # =========================
      - name: Debug spring-petclinica contents
        run: |
          echo "=== ROOT ==="
          ls -la
      
          echo "=== SPRING ==="
          ls -la spring-petclinica
          
      - name: Build Spring Petclinica
        run: |
          cd spring-petclinica
          mvn clean install -DskipTests


      # =========================
      # Levantar Spring Boot
      # =========================
      - name: Start Spring Boot
        run: |
          cd spring-petclinica
          nohup mvn spring-boot:run > spring.log 2>&1 &


      # =========================
      # Esperar API
      # equivalente al loop del BAT
      # =========================
      - name: Wait for Spring Boot
        run: |

          echo "Esperando Spring Boot..."

          until curl -s http://localhost:8080 > /dev/null
          do
            echo "Servidor no listo..."
            sleep 5
          done

          echo "Spring Boot listo"

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas plotly

      # =========================
      # Semgrep CI
      # =========================
      - name: Run Semgrep CI
        run: |
          semgrep ci \
          --config p/java \
          --exclude target \
          --exclude .git


      # =========================
      # k6
      # =========================
      - name: Setup k6
        uses: grafana/setup-k6-action@v1


      - name: Run k6 load test
        run: |

          mkdir -p results

          k6 run \
          --out json=results/resultado.json \
          k6-env/pet_clinic_test.js


      # =========================
      # Reporte k6
      # =========================
      - name: Generate k6 report
        run: |
          python k6-env/generar_reporte.py
      
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-report
          path: k6-env/results/*.html

      # =========================
      # SonarQube Server
      # =========================
      - name: SonarCloud Analysis
        run: |
          cd spring-petclinica
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
